objects:
- <<: (( merge ))
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: jitsi-config
  data:
    TZ: ${TZ}
    LOG_LEVEL: ${LOG_LEVEL}
    ENABLE_AUTH: ${ENABLE_AUTH}
    ENABLE_GUESTS: ${ENABLE_GUESTS}
    ENABLE_LOBBY: ${ENABLE_LOBBY}
    ENABLE_AUTO_OWNER: ${ENABLE_AUTO_OWNER}
    ENABLE_CODEC_VP8: ${ENABLE_CODEC_VP8}
    ENABLE_CODEC_VP9: ${ENABLE_CODEC_VP9}
    ENABLE_CODEC_H264: ${ENABLE_CODEC_H264}
    ENABLE_RECORDING: ${ENABLE_RECORDING}
    ENABLE_LETSENCRYPT: ${ENABLE_LETSENCRYPT}
    ENABLE_HTTP_REDIRECT: ${ENABLE_HTTP_REDIRECT}
    ENABLE_HSTS: ${ENABLE_HSTS}
    ENABLE_XMPP_WEBSOCKET: ${ENABLE_XMPP_WEBSOCKET}
    ENABLE_TRANSCRIPTIONS: ${ENABLE_TRANSCRIPTIONS}
    AUTH_TYPE: ${AUTH_TYPE}
    DISABLE_HTTPS: ${DISABLE_HTTPS}
    LETSENCRYPT_DOMAIN: ${DOMAIN}
    LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    LETSENCRYPT_USE_STAGING: ${LETSENCRYPT_USE_STAGING}
    PUBLIC_URL: https://${DOMAIN}
    XMPP_DOMAIN: ${DOMAIN}
    XMPP_AUTH_DOMAIN: "auth.${DOMAIN}"
    XMPP_GUEST_DOMAIN: "guest.${DOMAIN}"
    XMPP_MUC_DOMAIN: "muc.${DOMAIN}"
    XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.${DOMAIN}"
    XMPP_RECORDER_DOMAIN: "recorder.${DOMAIN}"
    XMPP_CROSS_DOMAIN: ${XMPP_CROSS_DOMAIN}
    XMPP_MODULES: ${XMPP_MODULES}
    XMPP_MUC_MODULES: ${XMPP_MUC_MODULES}
    XMPP_INTERNAL_MUC_MODULES: ${XMPP_INTERNAL_MUC_MODULES}
    GLOABL_MODULES: ${XMPP_MODULES}
    JVB_BREWERY_MUC: ${JVB_BREWERY_MUC}
    JVB_TCP_HARVESTER_DISABLED: ${JVB_TCP_HARVESTER_DISABLED}
    JVB_STUN_SERVERS: ${JVB_STUN_SERVERS}
    JVB_ENABLE_APIS: ${JVB_ENABLE_APIS}
    BRIDGE_AVG_PARTICIPANT_STRESS: ${BRIDGE_AVG_PARTICIPANT_STRESS}
    BRIDGE_STRESS_THRESHOLD: ${BRIDGE_STRESS_THRESHOLD}
    MAX_BRIDGE_PARTICIPANTS: ${MAX_BRIDGE_PARTICIPANTS}
    OCTO_BRIDGE_SELECTION_STRATEGY: ${OCTO_BRIDGE_SELECTION_STRATEGY}
    JICOFO_RESERVATION_ENABLED: ${JICOFO_RESERVATION_ENABLED}
    JICOFO_RESERVATION_REST_BASE_URL: ${JICOFO_RESERVATION_REST_BASE_URL}
    JICOFO_ENABLE_HEALTH_CHECKS: "true"
    JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS: ${JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS}
    JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT: ${JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT}
    JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT: ${JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT}
    JICOFO_SHORT_ID: ${JICOFO_SHORT_ID}
    JIGASI_SIP_URI: ${JIGASI_SIP_URI}
    JIGASI_SIP_SERVER: ${JIGASI_SIP_SERVER}
    JIGASI_SIP_PORT: ${JIGASI_SIP_PORT}
    JIGASI_SIP_TRANSPORT: ${JIGASI_SIP_TRANSPORT}
    JIGASI_SIP_DEFAULT_ROOM: ${JIGASI_SIP_DEFAULT_ROOM}
    JIGASI_BREWERY_MUC: ${JIGASI_BREWERY_MUC}
    JIGASI_PORT_MIN: ${JIGASI_PORT_MIN}
    JIGASI_PORT_MAX: ${JIGASI_PORT_MAX}
    JIGASI_ENABLE_SDES_SRTP: ${JIGASI_ENABLE_SDES_SRTP}
    JIGASI_SIP_KEEP_ALIVE_METHOD: ${JIGASI_SIP_KEEP_ALIVE_METHOD}
    JIGASI_HEALTH_CHECK_SIP_URI: ${JIGASI_HEALTH_CHECK_SIP_URI}
    JIGASI_HEALTH_CHECK_INTERVAL: ${JIGASI_HEALTH_CHECK_INTERVAL}
    JIGASI_TRANSCRIBER_RECORD_AUDIO: ${JIGASI_TRANSCRIBER_RECORD_AUDIO}
    JIGASI_TRANSCRIBER_SEND_TXT: ${JIGASI_TRANSCRIBER_SEND_TXT}
    JIGASI_TRANSCRIBER_ADVERTISE_URL: ${JIGASI_TRANSCRIBER_ADVERTISE_URL}
    JIBRI_RECORDING_DIR: ${JIBRI_RECORDING_DIR}
    JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: ${JIBRI_FINALIZE_RECORDING_SCRIPT_PATH}
    JIBRI_BREWERY_MUC: ${JIBRI_BREWERY_MUC}
    JIBRI_REQUEST_RETRIES: ${JIBRI_REQUEST_RETRIES}
    JIBRI_PENDING_TIMEOUT: ${JIBRI_PENDING_TIMEOUT}
    JIBRI_STRIP_DOMAIN_JID: ${JIBRI_STRIP_DOMAIN_JID}
    JIBRI_LOGS_DIR: ${JIBRI_LOGS_DIR}
    JWT_APP_ID: ${JWT_APP_ID}
    JWT_ACCEPTED_ISSUERS: ${JWT_ACCEPTED_ISSUERS}
    JWT_ACCEPTED_AUDIENCES: ${JWT_ACCEPTED_AUDIENCES}
    JWT_ASAP_KEYSERVER: ${JWT_ASAP_KEYSERVER}
    JWT_ALLOW_EMPTY: ${JWT_ALLOW_EMPTY}
    JWT_AUTH_TYPE: ${JWT_AUTH_TYPE}
    JWT_TOKEN_AUTH_MODULE: ${JWT_TOKEN_AUTH_MODULE}
    LDAP_URL: ${LDAP_URL}
    LDAP_BASE: ${LDAP_BASE}
    LDAP_FILTER: ${LDAP_FILTER}
    LDAP_AUTH_METHOD: ${LDAP_AUTH_METHOD}
    LDAP_VERSION: ${LDAP_VERSION}
    LDAP_USE_TLS: ${LDAP_USE_TLS}
    LDAP_TLS_CIPHERS: ${LDAP_TLS_CIPHERS}
    LDAP_TLS_CHECK_PEER: ${LDAP_TLS_CHECK_PEER}
    LDAP_TLS_CACERT_FILE: ${LDAP_TLS_CACERT_FILE}
    LDAP_TLS_CACERT_DIR: ${LDAP_TLS_CACERT_DIR}
    LDAP_START_TLS: ${LDAP_START_TLS}
    AMPLITUDE_ID: ${AMPLITUDE_ID}
    ANALYTICS_SCRIPT_URLS: ${ANALYTICS_SCRIPT_URLS}
    ANALYTICS_WHITELISTED_EVENTS: ${ANALYTICS_WHITELISTED_EVENTS}
    BRIDGE_CHANNEL: ${BRIDGE_CHANNEL}
    CALLSTATS_CUSTOM_SCRIPT_URL: ${CALLSTATS_CUSTOM_SCRIPT_URL}
    CALLSTATS_ID: ${CALLSTATS_ID}
    CALLSTATS_SECRET: ${CALLSTATS_SECRET}
    CHROME_EXTENSION_BANNER_JSON: ${CHROME_EXTENSION_BANNER_JSON}
    CONFCODE_URL: ${CONFCODE_URL}
    CONFIG_EXTERNAL_CONNECT: ${CONFIG_EXTERNAL_CONNECT}
    DEPLOYMENTINFO_ENVIRONMENT: ${DEPLOYMENTINFO_ENVIRONMENT}
    DEPLOYMENTINFO_ENVIRONMENT_TYPE: ${DEPLOYMENTINFO_ENVIRONMENT_TYPE}
    DEPLOYMENTINFO_USERREGION: ${DEPLOYMENTINFO_USERREGION}
    DIALIN_NUMBERS_URL: ${DIALIN_NUMBERS_URL}
    DIALOUT_AUTH_URL: ${DIALOUT_AUTH_URL}
    DIALOUT_CODES_URL: ${DIALOUT_CODES_URL}
    DROPBOX_APPKEY: ${DROPBOX_APPKEY}
    DROPBOX_REDIRECT_URI: ${DROPBOX_REDIRECT_URI}
    DYNAMIC_BRANDING_URL: ${DYNAMIC_BRANDING_URL}
    ENABLE_AUDIO_PROCESSING: ${ENABLE_AUDIO_PROCESSING}
    ENABLE_CALENDAR: ${ENABLE_CALENDAR}
    ENABLE_FILE_RECORDING_SERVICE: ${ENABLE_FILE_RECORDING_SERVICE}
    ENABLE_FILE_RECORDING_SERVICE_SHARING: ${ENABLE_FILE_RECORDING_SERVICE_SHARING}
    ENABLE_IPV6: ${ENABLE_IPV6}
    ENABLE_LIPSYNC: ${ENABLE_LIPSYNC}
    ENABLE_NO_AUDIO_DETECTION: ${ENABLE_NO_AUDIO_DETECTION}
    ENABLE_P2P: ${ENABLE_P2P}
    ENABLE_PREJOIN_PAGE: ${ENABLE_PREJOIN_PAGE}
    ENABLE_WELCOME_PAGE: ${ENABLE_WELCOME_PAGE}
    ENABLE_CLOSE_PAGE: ${ENABLE_CLOSE_PAGE}
    ENABLE_REMB: ${ENABLE_REMB}
    ENABLE_REQUIRE_DISPLAY_NAME: ${ENABLE_REQUIRE_DISPLAY_NAME}
    ENABLE_SIMULCAST: ${ENABLE_SIMULCAST}
    ENABLE_STATS_ID: ${ENABLE_STATS_ID}
    ENABLE_STEREO: ${ENABLE_STEREO}
    ENABLE_SUBDOMAINS: ${ENABLE_SUBDOMAINS}
    ENABLE_TALK_WHILE_MUTED: ${ENABLE_TALK_WHILE_MUTED}
    ENABLE_TCC: ${ENABLE_TCC}
    ETHERPAD_PUBLIC_URL: ${ETHERPAD_PUBLIC_URL}
    GOOGLE_ANALYTICS_ID: ${GOOGLE_ANALYTICS_ID}
    GOOGLE_API_APP_CLIENT_ID: ${GOOGLE_API_APP_CLIENT_ID}
    MATOMO_ENDPOINT: ${MATOMO_ENDPOINT}
    MATOMO_SITE_ID: ${MATOMO_SITE_ID}
    INVITE_SERVICE_URL: ${INVITE_SERVICE_URL}
    MICROSOFT_API_APP_CLIENT_ID: ${MICROSOFT_API_APP_CLIENT_ID}
    NGINX_RESOLVER: ${NGINX_RESOLVER}
    NGINX_WORKER_PROCESSES: ${NGINX_WORKER_PROCESSES}
    NGINX_WORKER_CONNECTIONS: ${NGINX_WORKER_CONNECTIONS}
    PEOPLE_SEARCH_URL: ${PEOPLE_SEARCH_URL}
    RESOLUTION: ${RESOLUTION}
    RESOLUTION_MIN: ${RESOLUTION_MIN}
    RESOLUTION_WIDTH: ${RESOLUTION_WIDTH}
    RESOLUTION_WIDTH_MIN: ${RESOLUTION_WIDTH_MIN}
    START_AUDIO_ONLY: ${START_AUDIO_ONLY}
    START_AUDIO_MUTED: ${START_AUDIO_MUTED}
    DISABLE_AUDIO_LEVELS: ${DISABLE_AUDIO_LEVELS}
    ENABLE_NOISY_MIC_DETECTION: ${ENABLE_NOISY_MIC_DETECTION}
    START_BITRATE: ${START_BITRATE}
    DESKTOP_SHARING_FRAMERATE_MIN: ${DESKTOP_SHARING_FRAMERATE_MIN}
    DESKTOP_SHARING_FRAMERATE_MAX: ${DESKTOP_SHARING_FRAMERATE_MAX}
    START_VIDEO_MUTED: ${START_VIDEO_MUTED}
    TESTING_CAP_SCREENSHARE_BITRATE: ${TESTING_CAP_SCREENSHARE_BITRATE}
    TESTING_OCTO_PROBABILITY: ${TESTING_OCTO_PROBABILITY}
