objects:
- <<: (( merge ))
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: jitsi
    name: etherpad
  spec:
    replicas: 1
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: jitsi
          name: etherpad
      spec:
        containers:
        - env:
          - name: TITLE
            value: ${ETHERPAD_TITLE}
          - name: DEFAULT_PAD_TEXT
            value: ${ETHERPAD_DEFAULT_PAD_TEXT}
          - name: SKIN_NAME
            value: ${ETHERPAD_SKIN_NAME}
          - name: SKIN_VARIANTS
            value: ${ETHERPAD_SKIN_VARIANTS}
          image: etherpad/etherpad
          imagePullPolicy: Always
          name: etherpad
          readinessProbe:
            httpGet:
              path: /
              port: 9001
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: 9001
            initialDelaySeconds: 120
            periodSeconds: 10
          ports:
          - containerPort: 9001
          resources: {}
        restartPolicy: Always
    triggers:
    - type: ConfigChange
  status: {}
